/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var frontier_v1_resources_pb = require('../frontier/v1/resources_pb.js');
goog.object.extend(proto, frontier_v1_resources_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_api_annotations_pb = require('../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var protoc$gen$swagger_options_annotations_pb = require('../protoc-gen-swagger/options/annotations_pb.js');
goog.object.extend(proto, protoc$gen$swagger_options_annotations_pb);
goog.exportSymbol('proto.veidemann.api.AbortCrawlRequest', null, global);
goog.exportSymbol('proto.veidemann.api.ExecutionId', null, global);
goog.exportSymbol('proto.veidemann.api.ExecutionsListReply', null, global);
goog.exportSymbol('proto.veidemann.api.JobExecutionsListReply', null, global);
goog.exportSymbol('proto.veidemann.api.ListExecutionsRequest', null, global);
goog.exportSymbol('proto.veidemann.api.ListJobExecutionsRequest', null, global);
goog.exportSymbol('proto.veidemann.api.RunningExecutionsListReply', null, global);
goog.exportSymbol('proto.veidemann.api.RunningExecutionsRequest', null, global);
goog.exportSymbol('proto.veidemann.api.StatusDetail', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.veidemann.api.RunningExecutionsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.veidemann.api.RunningExecutionsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.veidemann.api.RunningExecutionsRequest.displayName = 'proto.veidemann.api.RunningExecutionsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.veidemann.api.RunningExecutionsListReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.veidemann.api.RunningExecutionsListReply.repeatedFields_, null);
};
goog.inherits(proto.veidemann.api.RunningExecutionsListReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.veidemann.api.RunningExecutionsListReply.displayName = 'proto.veidemann.api.RunningExecutionsListReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.veidemann.api.StatusDetail = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.veidemann.api.StatusDetail, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.veidemann.api.StatusDetail.displayName = 'proto.veidemann.api.StatusDetail';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.veidemann.api.ExecutionId = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.veidemann.api.ExecutionId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.veidemann.api.ExecutionId.displayName = 'proto.veidemann.api.ExecutionId';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.veidemann.api.ListExecutionsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.veidemann.api.ListExecutionsRequest.repeatedFields_, null);
};
goog.inherits(proto.veidemann.api.ListExecutionsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.veidemann.api.ListExecutionsRequest.displayName = 'proto.veidemann.api.ListExecutionsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.veidemann.api.ListJobExecutionsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.veidemann.api.ListJobExecutionsRequest.repeatedFields_, null);
};
goog.inherits(proto.veidemann.api.ListJobExecutionsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.veidemann.api.ListJobExecutionsRequest.displayName = 'proto.veidemann.api.ListJobExecutionsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.veidemann.api.ExecutionsListReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.veidemann.api.ExecutionsListReply.repeatedFields_, null);
};
goog.inherits(proto.veidemann.api.ExecutionsListReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.veidemann.api.ExecutionsListReply.displayName = 'proto.veidemann.api.ExecutionsListReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.veidemann.api.JobExecutionsListReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.veidemann.api.JobExecutionsListReply.repeatedFields_, null);
};
goog.inherits(proto.veidemann.api.JobExecutionsListReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.veidemann.api.JobExecutionsListReply.displayName = 'proto.veidemann.api.JobExecutionsListReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.veidemann.api.AbortCrawlRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.veidemann.api.AbortCrawlRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.veidemann.api.AbortCrawlRequest.displayName = 'proto.veidemann.api.AbortCrawlRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.veidemann.api.RunningExecutionsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.veidemann.api.RunningExecutionsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.veidemann.api.RunningExecutionsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.RunningExecutionsRequest.toObject = function(includeInstance, msg) {
  var obj = {
    pageSize: jspb.Message.getFieldWithDefault(msg, 14, 0),
    page: jspb.Message.getFieldWithDefault(msg, 15, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.veidemann.api.RunningExecutionsRequest}
 */
proto.veidemann.api.RunningExecutionsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.veidemann.api.RunningExecutionsRequest;
  return proto.veidemann.api.RunningExecutionsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.veidemann.api.RunningExecutionsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.veidemann.api.RunningExecutionsRequest}
 */
proto.veidemann.api.RunningExecutionsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageSize(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.veidemann.api.RunningExecutionsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.veidemann.api.RunningExecutionsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.veidemann.api.RunningExecutionsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.RunningExecutionsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPageSize();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
};


/**
 * optional int32 page_size = 14;
 * @return {number}
 */
proto.veidemann.api.RunningExecutionsRequest.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/** @param {number} value */
proto.veidemann.api.RunningExecutionsRequest.prototype.setPageSize = function(value) {
  jspb.Message.setProto3IntField(this, 14, value);
};


Object.defineProperty(proto.veidemann.api.RunningExecutionsRequest.prototype, "pageSize", {
  set: function(value) {
    this.setPageSize(value);
  },
  get: function() {
    return this.getPageSize();
  },
});


/**
 * optional int32 page = 15;
 * @return {number}
 */
proto.veidemann.api.RunningExecutionsRequest.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/** @param {number} value */
proto.veidemann.api.RunningExecutionsRequest.prototype.setPage = function(value) {
  jspb.Message.setProto3IntField(this, 15, value);
};


Object.defineProperty(proto.veidemann.api.RunningExecutionsRequest.prototype, "page", {
  set: function(value) {
    this.setPage(value);
  },
  get: function() {
    return this.getPage();
  },
});



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.veidemann.api.RunningExecutionsListReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.veidemann.api.RunningExecutionsListReply.prototype.toObject = function(opt_includeInstance) {
  return proto.veidemann.api.RunningExecutionsListReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.veidemann.api.RunningExecutionsListReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.RunningExecutionsListReply.toObject = function(includeInstance, msg) {
  var obj = {
    valueList: jspb.Message.toObjectList(msg.getValueList(),
    proto.veidemann.api.StatusDetail.toObject, includeInstance),
    count: jspb.Message.getFieldWithDefault(msg, 2, 0),
    pageSize: jspb.Message.getFieldWithDefault(msg, 14, 0),
    page: jspb.Message.getFieldWithDefault(msg, 15, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.veidemann.api.RunningExecutionsListReply}
 */
proto.veidemann.api.RunningExecutionsListReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.veidemann.api.RunningExecutionsListReply;
  return proto.veidemann.api.RunningExecutionsListReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.veidemann.api.RunningExecutionsListReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.veidemann.api.RunningExecutionsListReply}
 */
proto.veidemann.api.RunningExecutionsListReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.veidemann.api.StatusDetail;
      reader.readMessage(value,proto.veidemann.api.StatusDetail.deserializeBinaryFromReader);
      msg.addValue(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCount(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageSize(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.veidemann.api.RunningExecutionsListReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.veidemann.api.RunningExecutionsListReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.veidemann.api.RunningExecutionsListReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.RunningExecutionsListReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValueList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.veidemann.api.StatusDetail.serializeBinaryToWriter
    );
  }
  f = message.getCount();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getPageSize();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
};


/**
 * repeated StatusDetail value = 1;
 * @return {!Array<!proto.veidemann.api.StatusDetail>}
 */
proto.veidemann.api.RunningExecutionsListReply.prototype.getValueList = function() {
  return /** @type{!Array<!proto.veidemann.api.StatusDetail>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.veidemann.api.StatusDetail, 1));
};


/** @param {!Array<!proto.veidemann.api.StatusDetail>} value */
proto.veidemann.api.RunningExecutionsListReply.prototype.setValueList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.veidemann.api.StatusDetail=} opt_value
 * @param {number=} opt_index
 * @return {!proto.veidemann.api.StatusDetail}
 */
proto.veidemann.api.RunningExecutionsListReply.prototype.addValue = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.veidemann.api.StatusDetail, opt_index);
};


Object.defineProperty(proto.veidemann.api.RunningExecutionsListReply.prototype, "valueList", {
  set: function(value) {
    this.setValueList(value);
  },
  get: function() {
    return this.getValueList();
  },
});


/**
 * Clears the list making it empty but non-null.
 */
proto.veidemann.api.RunningExecutionsListReply.prototype.clearValueList = function() {
  this.setValueList([]);
};


/**
 * optional int64 count = 2;
 * @return {number}
 */
proto.veidemann.api.RunningExecutionsListReply.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.veidemann.api.RunningExecutionsListReply.prototype.setCount = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


Object.defineProperty(proto.veidemann.api.RunningExecutionsListReply.prototype, "count", {
  set: function(value) {
    this.setCount(value);
  },
  get: function() {
    return this.getCount();
  },
});


/**
 * optional int32 page_size = 14;
 * @return {number}
 */
proto.veidemann.api.RunningExecutionsListReply.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/** @param {number} value */
proto.veidemann.api.RunningExecutionsListReply.prototype.setPageSize = function(value) {
  jspb.Message.setProto3IntField(this, 14, value);
};


Object.defineProperty(proto.veidemann.api.RunningExecutionsListReply.prototype, "pageSize", {
  set: function(value) {
    this.setPageSize(value);
  },
  get: function() {
    return this.getPageSize();
  },
});


/**
 * optional int32 page = 15;
 * @return {number}
 */
proto.veidemann.api.RunningExecutionsListReply.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/** @param {number} value */
proto.veidemann.api.RunningExecutionsListReply.prototype.setPage = function(value) {
  jspb.Message.setProto3IntField(this, 15, value);
};


Object.defineProperty(proto.veidemann.api.RunningExecutionsListReply.prototype, "page", {
  set: function(value) {
    this.setPage(value);
  },
  get: function() {
    return this.getPage();
  },
});





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.veidemann.api.StatusDetail.prototype.toObject = function(opt_includeInstance) {
  return proto.veidemann.api.StatusDetail.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.veidemann.api.StatusDetail} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.StatusDetail.toObject = function(includeInstance, msg) {
  var obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    state: jspb.Message.getFieldWithDefault(msg, 2, 0),
    jobid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    seed: jspb.Message.getFieldWithDefault(msg, 4, ""),
    startTime: (f = msg.getStartTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    endTime: (f = msg.getEndTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    documentsCrawled: jspb.Message.getFieldWithDefault(msg, 7, 0),
    bytesCrawled: jspb.Message.getFieldWithDefault(msg, 8, 0),
    urisCrawled: jspb.Message.getFieldWithDefault(msg, 9, 0),
    documentsFailed: jspb.Message.getFieldWithDefault(msg, 10, 0),
    documentsOutOfScope: jspb.Message.getFieldWithDefault(msg, 11, 0),
    documentsRetried: jspb.Message.getFieldWithDefault(msg, 12, 0),
    documentsDenied: jspb.Message.getFieldWithDefault(msg, 13, 0),
    queueSize: jspb.Message.getFieldWithDefault(msg, 14, 0),
    currentUri: jspb.Message.getFieldWithDefault(msg, 20, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.veidemann.api.StatusDetail}
 */
proto.veidemann.api.StatusDetail.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.veidemann.api.StatusDetail;
  return proto.veidemann.api.StatusDetail.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.veidemann.api.StatusDetail} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.veidemann.api.StatusDetail}
 */
proto.veidemann.api.StatusDetail.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {!proto.veidemann.api.frontier.v1.CrawlExecutionStatus.State} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSeed(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStartTime(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEndTime(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDocumentsCrawled(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBytesCrawled(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUrisCrawled(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDocumentsFailed(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDocumentsOutOfScope(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDocumentsRetried(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDocumentsDenied(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setQueueSize(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrentUri(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.veidemann.api.StatusDetail.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.veidemann.api.StatusDetail.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.veidemann.api.StatusDetail} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.StatusDetail.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getJobid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSeed();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getStartTime();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEndTime();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDocumentsCrawled();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getBytesCrawled();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getUrisCrawled();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getDocumentsFailed();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = message.getDocumentsOutOfScope();
  if (f !== 0) {
    writer.writeInt64(
      11,
      f
    );
  }
  f = message.getDocumentsRetried();
  if (f !== 0) {
    writer.writeInt64(
      12,
      f
    );
  }
  f = message.getDocumentsDenied();
  if (f !== 0) {
    writer.writeInt64(
      13,
      f
    );
  }
  f = message.getQueueSize();
  if (f !== 0) {
    writer.writeInt64(
      14,
      f
    );
  }
  f = message.getCurrentUri();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.veidemann.api.StatusDetail.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.veidemann.api.StatusDetail.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


Object.defineProperty(proto.veidemann.api.StatusDetail.prototype, "id", {
  set: function(value) {
    this.setId(value);
  },
  get: function() {
    return this.getId();
  },
});


/**
 * optional frontier.v1.CrawlExecutionStatus.State state = 2;
 * @return {!proto.veidemann.api.frontier.v1.CrawlExecutionStatus.State}
 */
proto.veidemann.api.StatusDetail.prototype.getState = function() {
  return /** @type {!proto.veidemann.api.frontier.v1.CrawlExecutionStatus.State} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.veidemann.api.frontier.v1.CrawlExecutionStatus.State} value */
proto.veidemann.api.StatusDetail.prototype.setState = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


Object.defineProperty(proto.veidemann.api.StatusDetail.prototype, "state", {
  set: function(value) {
    this.setState(value);
  },
  get: function() {
    return this.getState();
  },
});


/**
 * optional string jobId = 3;
 * @return {string}
 */
proto.veidemann.api.StatusDetail.prototype.getJobid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.veidemann.api.StatusDetail.prototype.setJobid = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


Object.defineProperty(proto.veidemann.api.StatusDetail.prototype, "jobid", {
  set: function(value) {
    this.setJobid(value);
  },
  get: function() {
    return this.getJobid();
  },
});


/**
 * optional string seed = 4;
 * @return {string}
 */
proto.veidemann.api.StatusDetail.prototype.getSeed = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.veidemann.api.StatusDetail.prototype.setSeed = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


Object.defineProperty(proto.veidemann.api.StatusDetail.prototype, "seed", {
  set: function(value) {
    this.setSeed(value);
  },
  get: function() {
    return this.getSeed();
  },
});


/**
 * optional google.protobuf.Timestamp start_time = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.veidemann.api.StatusDetail.prototype.getStartTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.veidemann.api.StatusDetail.prototype.setStartTime = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


Object.defineProperty(proto.veidemann.api.StatusDetail.prototype, "startTime", {
  set: function(value) {
    this.setStartTime(value);
  },
  get: function() {
    return this.getStartTime();
  },
});


/**
 * Clears the message field making it undefined.
 */
proto.veidemann.api.StatusDetail.prototype.clearStartTime = function() {
  this.setStartTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.veidemann.api.StatusDetail.prototype.hasStartTime = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Timestamp end_time = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.veidemann.api.StatusDetail.prototype.getEndTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.veidemann.api.StatusDetail.prototype.setEndTime = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


Object.defineProperty(proto.veidemann.api.StatusDetail.prototype, "endTime", {
  set: function(value) {
    this.setEndTime(value);
  },
  get: function() {
    return this.getEndTime();
  },
});


/**
 * Clears the message field making it undefined.
 */
proto.veidemann.api.StatusDetail.prototype.clearEndTime = function() {
  this.setEndTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.veidemann.api.StatusDetail.prototype.hasEndTime = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional int64 documents_crawled = 7;
 * @return {number}
 */
proto.veidemann.api.StatusDetail.prototype.getDocumentsCrawled = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.veidemann.api.StatusDetail.prototype.setDocumentsCrawled = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


Object.defineProperty(proto.veidemann.api.StatusDetail.prototype, "documentsCrawled", {
  set: function(value) {
    this.setDocumentsCrawled(value);
  },
  get: function() {
    return this.getDocumentsCrawled();
  },
});


/**
 * optional int64 bytes_crawled = 8;
 * @return {number}
 */
proto.veidemann.api.StatusDetail.prototype.getBytesCrawled = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.veidemann.api.StatusDetail.prototype.setBytesCrawled = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


Object.defineProperty(proto.veidemann.api.StatusDetail.prototype, "bytesCrawled", {
  set: function(value) {
    this.setBytesCrawled(value);
  },
  get: function() {
    return this.getBytesCrawled();
  },
});


/**
 * optional int64 uris_crawled = 9;
 * @return {number}
 */
proto.veidemann.api.StatusDetail.prototype.getUrisCrawled = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.veidemann.api.StatusDetail.prototype.setUrisCrawled = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


Object.defineProperty(proto.veidemann.api.StatusDetail.prototype, "urisCrawled", {
  set: function(value) {
    this.setUrisCrawled(value);
  },
  get: function() {
    return this.getUrisCrawled();
  },
});


/**
 * optional int64 documents_failed = 10;
 * @return {number}
 */
proto.veidemann.api.StatusDetail.prototype.getDocumentsFailed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.veidemann.api.StatusDetail.prototype.setDocumentsFailed = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


Object.defineProperty(proto.veidemann.api.StatusDetail.prototype, "documentsFailed", {
  set: function(value) {
    this.setDocumentsFailed(value);
  },
  get: function() {
    return this.getDocumentsFailed();
  },
});


/**
 * optional int64 documents_out_of_scope = 11;
 * @return {number}
 */
proto.veidemann.api.StatusDetail.prototype.getDocumentsOutOfScope = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {number} value */
proto.veidemann.api.StatusDetail.prototype.setDocumentsOutOfScope = function(value) {
  jspb.Message.setProto3IntField(this, 11, value);
};


Object.defineProperty(proto.veidemann.api.StatusDetail.prototype, "documentsOutOfScope", {
  set: function(value) {
    this.setDocumentsOutOfScope(value);
  },
  get: function() {
    return this.getDocumentsOutOfScope();
  },
});


/**
 * optional int64 documents_retried = 12;
 * @return {number}
 */
proto.veidemann.api.StatusDetail.prototype.getDocumentsRetried = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/** @param {number} value */
proto.veidemann.api.StatusDetail.prototype.setDocumentsRetried = function(value) {
  jspb.Message.setProto3IntField(this, 12, value);
};


Object.defineProperty(proto.veidemann.api.StatusDetail.prototype, "documentsRetried", {
  set: function(value) {
    this.setDocumentsRetried(value);
  },
  get: function() {
    return this.getDocumentsRetried();
  },
});


/**
 * optional int64 documents_denied = 13;
 * @return {number}
 */
proto.veidemann.api.StatusDetail.prototype.getDocumentsDenied = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/** @param {number} value */
proto.veidemann.api.StatusDetail.prototype.setDocumentsDenied = function(value) {
  jspb.Message.setProto3IntField(this, 13, value);
};


Object.defineProperty(proto.veidemann.api.StatusDetail.prototype, "documentsDenied", {
  set: function(value) {
    this.setDocumentsDenied(value);
  },
  get: function() {
    return this.getDocumentsDenied();
  },
});


/**
 * optional int64 queue_size = 14;
 * @return {number}
 */
proto.veidemann.api.StatusDetail.prototype.getQueueSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/** @param {number} value */
proto.veidemann.api.StatusDetail.prototype.setQueueSize = function(value) {
  jspb.Message.setProto3IntField(this, 14, value);
};


Object.defineProperty(proto.veidemann.api.StatusDetail.prototype, "queueSize", {
  set: function(value) {
    this.setQueueSize(value);
  },
  get: function() {
    return this.getQueueSize();
  },
});


/**
 * optional string current_uri = 20;
 * @return {string}
 */
proto.veidemann.api.StatusDetail.prototype.getCurrentUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/** @param {string} value */
proto.veidemann.api.StatusDetail.prototype.setCurrentUri = function(value) {
  jspb.Message.setProto3StringField(this, 20, value);
};


Object.defineProperty(proto.veidemann.api.StatusDetail.prototype, "currentUri", {
  set: function(value) {
    this.setCurrentUri(value);
  },
  get: function() {
    return this.getCurrentUri();
  },
});





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.veidemann.api.ExecutionId.prototype.toObject = function(opt_includeInstance) {
  return proto.veidemann.api.ExecutionId.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.veidemann.api.ExecutionId} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.ExecutionId.toObject = function(includeInstance, msg) {
  var obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.veidemann.api.ExecutionId}
 */
proto.veidemann.api.ExecutionId.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.veidemann.api.ExecutionId;
  return proto.veidemann.api.ExecutionId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.veidemann.api.ExecutionId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.veidemann.api.ExecutionId}
 */
proto.veidemann.api.ExecutionId.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.veidemann.api.ExecutionId.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.veidemann.api.ExecutionId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.veidemann.api.ExecutionId} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.ExecutionId.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.veidemann.api.ExecutionId.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.veidemann.api.ExecutionId.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


Object.defineProperty(proto.veidemann.api.ExecutionId.prototype, "id", {
  set: function(value) {
    this.setId(value);
  },
  get: function() {
    return this.getId();
  },
});



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.veidemann.api.ListExecutionsRequest.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.veidemann.api.ListExecutionsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.veidemann.api.ListExecutionsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.veidemann.api.ListExecutionsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.ListExecutionsRequest.toObject = function(includeInstance, msg) {
  var obj = {
    idList: jspb.Message.getRepeatedField(msg, 1),
    stateList: jspb.Message.getRepeatedField(msg, 2),
    seedId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    jobId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    jobExecutionId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    pageSize: jspb.Message.getFieldWithDefault(msg, 14, 0),
    page: jspb.Message.getFieldWithDefault(msg, 15, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.veidemann.api.ListExecutionsRequest}
 */
proto.veidemann.api.ListExecutionsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.veidemann.api.ListExecutionsRequest;
  return proto.veidemann.api.ListExecutionsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.veidemann.api.ListExecutionsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.veidemann.api.ListExecutionsRequest}
 */
proto.veidemann.api.ListExecutionsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addState(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSeedId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobExecutionId(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageSize(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.veidemann.api.ListExecutionsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.veidemann.api.ListExecutionsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.veidemann.api.ListExecutionsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.ListExecutionsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getStateList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getSeedId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getJobId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getJobExecutionId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getPageSize();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
};


/**
 * repeated string id = 1;
 * @return {!Array<string>}
 */
proto.veidemann.api.ListExecutionsRequest.prototype.getIdList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array<string>} value */
proto.veidemann.api.ListExecutionsRequest.prototype.setIdList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.veidemann.api.ListExecutionsRequest.prototype.addId = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


Object.defineProperty(proto.veidemann.api.ListExecutionsRequest.prototype, "idList", {
  set: function(value) {
    this.setIdList(value);
  },
  get: function() {
    return this.getIdList();
  },
});


/**
 * Clears the list making it empty but non-null.
 */
proto.veidemann.api.ListExecutionsRequest.prototype.clearIdList = function() {
  this.setIdList([]);
};


/**
 * repeated string state = 2;
 * @return {!Array<string>}
 */
proto.veidemann.api.ListExecutionsRequest.prototype.getStateList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.veidemann.api.ListExecutionsRequest.prototype.setStateList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.veidemann.api.ListExecutionsRequest.prototype.addState = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


Object.defineProperty(proto.veidemann.api.ListExecutionsRequest.prototype, "stateList", {
  set: function(value) {
    this.setStateList(value);
  },
  get: function() {
    return this.getStateList();
  },
});


/**
 * Clears the list making it empty but non-null.
 */
proto.veidemann.api.ListExecutionsRequest.prototype.clearStateList = function() {
  this.setStateList([]);
};


/**
 * optional string seed_id = 3;
 * @return {string}
 */
proto.veidemann.api.ListExecutionsRequest.prototype.getSeedId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.veidemann.api.ListExecutionsRequest.prototype.setSeedId = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


Object.defineProperty(proto.veidemann.api.ListExecutionsRequest.prototype, "seedId", {
  set: function(value) {
    this.setSeedId(value);
  },
  get: function() {
    return this.getSeedId();
  },
});


/**
 * optional string job_id = 4;
 * @return {string}
 */
proto.veidemann.api.ListExecutionsRequest.prototype.getJobId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.veidemann.api.ListExecutionsRequest.prototype.setJobId = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


Object.defineProperty(proto.veidemann.api.ListExecutionsRequest.prototype, "jobId", {
  set: function(value) {
    this.setJobId(value);
  },
  get: function() {
    return this.getJobId();
  },
});


/**
 * optional string job_execution_id = 5;
 * @return {string}
 */
proto.veidemann.api.ListExecutionsRequest.prototype.getJobExecutionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.veidemann.api.ListExecutionsRequest.prototype.setJobExecutionId = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


Object.defineProperty(proto.veidemann.api.ListExecutionsRequest.prototype, "jobExecutionId", {
  set: function(value) {
    this.setJobExecutionId(value);
  },
  get: function() {
    return this.getJobExecutionId();
  },
});


/**
 * optional int32 page_size = 14;
 * @return {number}
 */
proto.veidemann.api.ListExecutionsRequest.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/** @param {number} value */
proto.veidemann.api.ListExecutionsRequest.prototype.setPageSize = function(value) {
  jspb.Message.setProto3IntField(this, 14, value);
};


Object.defineProperty(proto.veidemann.api.ListExecutionsRequest.prototype, "pageSize", {
  set: function(value) {
    this.setPageSize(value);
  },
  get: function() {
    return this.getPageSize();
  },
});


/**
 * optional int32 page = 15;
 * @return {number}
 */
proto.veidemann.api.ListExecutionsRequest.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/** @param {number} value */
proto.veidemann.api.ListExecutionsRequest.prototype.setPage = function(value) {
  jspb.Message.setProto3IntField(this, 15, value);
};


Object.defineProperty(proto.veidemann.api.ListExecutionsRequest.prototype, "page", {
  set: function(value) {
    this.setPage(value);
  },
  get: function() {
    return this.getPage();
  },
});



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.veidemann.api.ListJobExecutionsRequest.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.veidemann.api.ListJobExecutionsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.veidemann.api.ListJobExecutionsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.veidemann.api.ListJobExecutionsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.ListJobExecutionsRequest.toObject = function(includeInstance, msg) {
  var obj = {
    idList: jspb.Message.getRepeatedField(msg, 1),
    stateList: jspb.Message.getRepeatedField(msg, 2),
    jobId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    pageSize: jspb.Message.getFieldWithDefault(msg, 14, 0),
    page: jspb.Message.getFieldWithDefault(msg, 15, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.veidemann.api.ListJobExecutionsRequest}
 */
proto.veidemann.api.ListJobExecutionsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.veidemann.api.ListJobExecutionsRequest;
  return proto.veidemann.api.ListJobExecutionsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.veidemann.api.ListJobExecutionsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.veidemann.api.ListJobExecutionsRequest}
 */
proto.veidemann.api.ListJobExecutionsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addState(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobId(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageSize(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.veidemann.api.ListJobExecutionsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.veidemann.api.ListJobExecutionsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.veidemann.api.ListJobExecutionsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.ListJobExecutionsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getStateList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getJobId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPageSize();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
};


/**
 * repeated string id = 1;
 * @return {!Array<string>}
 */
proto.veidemann.api.ListJobExecutionsRequest.prototype.getIdList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array<string>} value */
proto.veidemann.api.ListJobExecutionsRequest.prototype.setIdList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.veidemann.api.ListJobExecutionsRequest.prototype.addId = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


Object.defineProperty(proto.veidemann.api.ListJobExecutionsRequest.prototype, "idList", {
  set: function(value) {
    this.setIdList(value);
  },
  get: function() {
    return this.getIdList();
  },
});


/**
 * Clears the list making it empty but non-null.
 */
proto.veidemann.api.ListJobExecutionsRequest.prototype.clearIdList = function() {
  this.setIdList([]);
};


/**
 * repeated string state = 2;
 * @return {!Array<string>}
 */
proto.veidemann.api.ListJobExecutionsRequest.prototype.getStateList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.veidemann.api.ListJobExecutionsRequest.prototype.setStateList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.veidemann.api.ListJobExecutionsRequest.prototype.addState = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


Object.defineProperty(proto.veidemann.api.ListJobExecutionsRequest.prototype, "stateList", {
  set: function(value) {
    this.setStateList(value);
  },
  get: function() {
    return this.getStateList();
  },
});


/**
 * Clears the list making it empty but non-null.
 */
proto.veidemann.api.ListJobExecutionsRequest.prototype.clearStateList = function() {
  this.setStateList([]);
};


/**
 * optional string job_id = 4;
 * @return {string}
 */
proto.veidemann.api.ListJobExecutionsRequest.prototype.getJobId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.veidemann.api.ListJobExecutionsRequest.prototype.setJobId = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


Object.defineProperty(proto.veidemann.api.ListJobExecutionsRequest.prototype, "jobId", {
  set: function(value) {
    this.setJobId(value);
  },
  get: function() {
    return this.getJobId();
  },
});


/**
 * optional int32 page_size = 14;
 * @return {number}
 */
proto.veidemann.api.ListJobExecutionsRequest.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/** @param {number} value */
proto.veidemann.api.ListJobExecutionsRequest.prototype.setPageSize = function(value) {
  jspb.Message.setProto3IntField(this, 14, value);
};


Object.defineProperty(proto.veidemann.api.ListJobExecutionsRequest.prototype, "pageSize", {
  set: function(value) {
    this.setPageSize(value);
  },
  get: function() {
    return this.getPageSize();
  },
});


/**
 * optional int32 page = 15;
 * @return {number}
 */
proto.veidemann.api.ListJobExecutionsRequest.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/** @param {number} value */
proto.veidemann.api.ListJobExecutionsRequest.prototype.setPage = function(value) {
  jspb.Message.setProto3IntField(this, 15, value);
};


Object.defineProperty(proto.veidemann.api.ListJobExecutionsRequest.prototype, "page", {
  set: function(value) {
    this.setPage(value);
  },
  get: function() {
    return this.getPage();
  },
});



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.veidemann.api.ExecutionsListReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.veidemann.api.ExecutionsListReply.prototype.toObject = function(opt_includeInstance) {
  return proto.veidemann.api.ExecutionsListReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.veidemann.api.ExecutionsListReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.ExecutionsListReply.toObject = function(includeInstance, msg) {
  var obj = {
    valueList: jspb.Message.toObjectList(msg.getValueList(),
    frontier_v1_resources_pb.CrawlExecutionStatus.toObject, includeInstance),
    count: jspb.Message.getFieldWithDefault(msg, 2, 0),
    pageSize: jspb.Message.getFieldWithDefault(msg, 14, 0),
    page: jspb.Message.getFieldWithDefault(msg, 15, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.veidemann.api.ExecutionsListReply}
 */
proto.veidemann.api.ExecutionsListReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.veidemann.api.ExecutionsListReply;
  return proto.veidemann.api.ExecutionsListReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.veidemann.api.ExecutionsListReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.veidemann.api.ExecutionsListReply}
 */
proto.veidemann.api.ExecutionsListReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new frontier_v1_resources_pb.CrawlExecutionStatus;
      reader.readMessage(value,frontier_v1_resources_pb.CrawlExecutionStatus.deserializeBinaryFromReader);
      msg.addValue(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCount(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageSize(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.veidemann.api.ExecutionsListReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.veidemann.api.ExecutionsListReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.veidemann.api.ExecutionsListReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.ExecutionsListReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValueList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      frontier_v1_resources_pb.CrawlExecutionStatus.serializeBinaryToWriter
    );
  }
  f = message.getCount();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getPageSize();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
};


/**
 * repeated frontier.v1.CrawlExecutionStatus value = 1;
 * @return {!Array<!proto.veidemann.api.frontier.v1.CrawlExecutionStatus>}
 */
proto.veidemann.api.ExecutionsListReply.prototype.getValueList = function() {
  return /** @type{!Array<!proto.veidemann.api.frontier.v1.CrawlExecutionStatus>} */ (
    jspb.Message.getRepeatedWrapperField(this, frontier_v1_resources_pb.CrawlExecutionStatus, 1));
};


/** @param {!Array<!proto.veidemann.api.frontier.v1.CrawlExecutionStatus>} value */
proto.veidemann.api.ExecutionsListReply.prototype.setValueList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.veidemann.api.frontier.v1.CrawlExecutionStatus=} opt_value
 * @param {number=} opt_index
 * @return {!proto.veidemann.api.frontier.v1.CrawlExecutionStatus}
 */
proto.veidemann.api.ExecutionsListReply.prototype.addValue = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.veidemann.api.frontier.v1.CrawlExecutionStatus, opt_index);
};


Object.defineProperty(proto.veidemann.api.ExecutionsListReply.prototype, "valueList", {
  set: function(value) {
    this.setValueList(value);
  },
  get: function() {
    return this.getValueList();
  },
});


/**
 * Clears the list making it empty but non-null.
 */
proto.veidemann.api.ExecutionsListReply.prototype.clearValueList = function() {
  this.setValueList([]);
};


/**
 * optional int64 count = 2;
 * @return {number}
 */
proto.veidemann.api.ExecutionsListReply.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.veidemann.api.ExecutionsListReply.prototype.setCount = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


Object.defineProperty(proto.veidemann.api.ExecutionsListReply.prototype, "count", {
  set: function(value) {
    this.setCount(value);
  },
  get: function() {
    return this.getCount();
  },
});


/**
 * optional int32 page_size = 14;
 * @return {number}
 */
proto.veidemann.api.ExecutionsListReply.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/** @param {number} value */
proto.veidemann.api.ExecutionsListReply.prototype.setPageSize = function(value) {
  jspb.Message.setProto3IntField(this, 14, value);
};


Object.defineProperty(proto.veidemann.api.ExecutionsListReply.prototype, "pageSize", {
  set: function(value) {
    this.setPageSize(value);
  },
  get: function() {
    return this.getPageSize();
  },
});


/**
 * optional int32 page = 15;
 * @return {number}
 */
proto.veidemann.api.ExecutionsListReply.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/** @param {number} value */
proto.veidemann.api.ExecutionsListReply.prototype.setPage = function(value) {
  jspb.Message.setProto3IntField(this, 15, value);
};


Object.defineProperty(proto.veidemann.api.ExecutionsListReply.prototype, "page", {
  set: function(value) {
    this.setPage(value);
  },
  get: function() {
    return this.getPage();
  },
});



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.veidemann.api.JobExecutionsListReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.veidemann.api.JobExecutionsListReply.prototype.toObject = function(opt_includeInstance) {
  return proto.veidemann.api.JobExecutionsListReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.veidemann.api.JobExecutionsListReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.JobExecutionsListReply.toObject = function(includeInstance, msg) {
  var obj = {
    valueList: jspb.Message.toObjectList(msg.getValueList(),
    frontier_v1_resources_pb.JobExecutionStatus.toObject, includeInstance),
    count: jspb.Message.getFieldWithDefault(msg, 2, 0),
    pageSize: jspb.Message.getFieldWithDefault(msg, 14, 0),
    page: jspb.Message.getFieldWithDefault(msg, 15, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.veidemann.api.JobExecutionsListReply}
 */
proto.veidemann.api.JobExecutionsListReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.veidemann.api.JobExecutionsListReply;
  return proto.veidemann.api.JobExecutionsListReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.veidemann.api.JobExecutionsListReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.veidemann.api.JobExecutionsListReply}
 */
proto.veidemann.api.JobExecutionsListReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new frontier_v1_resources_pb.JobExecutionStatus;
      reader.readMessage(value,frontier_v1_resources_pb.JobExecutionStatus.deserializeBinaryFromReader);
      msg.addValue(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCount(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageSize(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.veidemann.api.JobExecutionsListReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.veidemann.api.JobExecutionsListReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.veidemann.api.JobExecutionsListReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.JobExecutionsListReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValueList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      frontier_v1_resources_pb.JobExecutionStatus.serializeBinaryToWriter
    );
  }
  f = message.getCount();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getPageSize();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
};


/**
 * repeated frontier.v1.JobExecutionStatus value = 1;
 * @return {!Array<!proto.veidemann.api.frontier.v1.JobExecutionStatus>}
 */
proto.veidemann.api.JobExecutionsListReply.prototype.getValueList = function() {
  return /** @type{!Array<!proto.veidemann.api.frontier.v1.JobExecutionStatus>} */ (
    jspb.Message.getRepeatedWrapperField(this, frontier_v1_resources_pb.JobExecutionStatus, 1));
};


/** @param {!Array<!proto.veidemann.api.frontier.v1.JobExecutionStatus>} value */
proto.veidemann.api.JobExecutionsListReply.prototype.setValueList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.veidemann.api.frontier.v1.JobExecutionStatus=} opt_value
 * @param {number=} opt_index
 * @return {!proto.veidemann.api.frontier.v1.JobExecutionStatus}
 */
proto.veidemann.api.JobExecutionsListReply.prototype.addValue = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.veidemann.api.frontier.v1.JobExecutionStatus, opt_index);
};


Object.defineProperty(proto.veidemann.api.JobExecutionsListReply.prototype, "valueList", {
  set: function(value) {
    this.setValueList(value);
  },
  get: function() {
    return this.getValueList();
  },
});


/**
 * Clears the list making it empty but non-null.
 */
proto.veidemann.api.JobExecutionsListReply.prototype.clearValueList = function() {
  this.setValueList([]);
};


/**
 * optional int64 count = 2;
 * @return {number}
 */
proto.veidemann.api.JobExecutionsListReply.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.veidemann.api.JobExecutionsListReply.prototype.setCount = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


Object.defineProperty(proto.veidemann.api.JobExecutionsListReply.prototype, "count", {
  set: function(value) {
    this.setCount(value);
  },
  get: function() {
    return this.getCount();
  },
});


/**
 * optional int32 page_size = 14;
 * @return {number}
 */
proto.veidemann.api.JobExecutionsListReply.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/** @param {number} value */
proto.veidemann.api.JobExecutionsListReply.prototype.setPageSize = function(value) {
  jspb.Message.setProto3IntField(this, 14, value);
};


Object.defineProperty(proto.veidemann.api.JobExecutionsListReply.prototype, "pageSize", {
  set: function(value) {
    this.setPageSize(value);
  },
  get: function() {
    return this.getPageSize();
  },
});


/**
 * optional int32 page = 15;
 * @return {number}
 */
proto.veidemann.api.JobExecutionsListReply.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/** @param {number} value */
proto.veidemann.api.JobExecutionsListReply.prototype.setPage = function(value) {
  jspb.Message.setProto3IntField(this, 15, value);
};


Object.defineProperty(proto.veidemann.api.JobExecutionsListReply.prototype, "page", {
  set: function(value) {
    this.setPage(value);
  },
  get: function() {
    return this.getPage();
  },
});





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.veidemann.api.AbortCrawlRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.veidemann.api.AbortCrawlRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.veidemann.api.AbortCrawlRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.AbortCrawlRequest.toObject = function(includeInstance, msg) {
  var obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.veidemann.api.AbortCrawlRequest}
 */
proto.veidemann.api.AbortCrawlRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.veidemann.api.AbortCrawlRequest;
  return proto.veidemann.api.AbortCrawlRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.veidemann.api.AbortCrawlRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.veidemann.api.AbortCrawlRequest}
 */
proto.veidemann.api.AbortCrawlRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.veidemann.api.AbortCrawlRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.veidemann.api.AbortCrawlRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.veidemann.api.AbortCrawlRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.AbortCrawlRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.veidemann.api.AbortCrawlRequest.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.veidemann.api.AbortCrawlRequest.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


Object.defineProperty(proto.veidemann.api.AbortCrawlRequest.prototype, "id", {
  set: function(value) {
    this.setId(value);
  },
  get: function() {
    return this.getId();
  },
});


goog.object.extend(exports, proto.veidemann.api);
