// source: log/v1/resources.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var commons_v1_resources_pb = require('../../commons/v1/resources_pb.d.ts');
goog.object.extend(proto, commons_v1_resources_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.veidemann.api.log.v1.CrawlLog', null, global);
goog.exportSymbol('proto.veidemann.api.log.v1.PageLog', null, global);
goog.exportSymbol('proto.veidemann.api.log.v1.PageLog.Resource', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.veidemann.api.log.v1.CrawlLog = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.veidemann.api.log.v1.CrawlLog, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.veidemann.api.log.v1.CrawlLog.displayName = 'proto.veidemann.api.log.v1.CrawlLog';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.veidemann.api.log.v1.PageLog = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.veidemann.api.log.v1.PageLog.repeatedFields_, null);
};
goog.inherits(proto.veidemann.api.log.v1.PageLog, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.veidemann.api.log.v1.PageLog.displayName = 'proto.veidemann.api.log.v1.PageLog';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.veidemann.api.log.v1.PageLog.Resource = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.veidemann.api.log.v1.PageLog.Resource, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.veidemann.api.log.v1.PageLog.Resource.displayName = 'proto.veidemann.api.log.v1.PageLog.Resource';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.toObject = function(opt_includeInstance) {
  return proto.veidemann.api.log.v1.CrawlLog.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.veidemann.api.log.v1.CrawlLog} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.log.v1.CrawlLog.toObject = function(includeInstance, msg) {
  var f, obj = {
    warcId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    timeStamp: (f = msg.getTimeStamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    statusCode: jspb.Message.getFieldWithDefault(msg, 4, 0),
    size: jspb.Message.getFieldWithDefault(msg, 5, 0),
    requestedUri: jspb.Message.getFieldWithDefault(msg, 6, ""),
    responseUri: jspb.Message.getFieldWithDefault(msg, 7, ""),
    discoveryPath: jspb.Message.getFieldWithDefault(msg, 8, ""),
    referrer: jspb.Message.getFieldWithDefault(msg, 9, ""),
    contentType: jspb.Message.getFieldWithDefault(msg, 10, ""),
    fetchTimeStamp: (f = msg.getFetchTimeStamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    fetchTimeMs: jspb.Message.getFieldWithDefault(msg, 12, 0),
    blockDigest: jspb.Message.getFieldWithDefault(msg, 13, ""),
    payloadDigest: jspb.Message.getFieldWithDefault(msg, 14, ""),
    storageRef: jspb.Message.getFieldWithDefault(msg, 15, ""),
    recordType: jspb.Message.getFieldWithDefault(msg, 16, ""),
    warcRefersTo: jspb.Message.getFieldWithDefault(msg, 17, ""),
    ipAddress: jspb.Message.getFieldWithDefault(msg, 18, ""),
    executionId: jspb.Message.getFieldWithDefault(msg, 19, ""),
    retries: jspb.Message.getFieldWithDefault(msg, 20, 0),
    error: (f = msg.getError()) && commons_v1_resources_pb.Error.toObject(includeInstance, f),
    jobExecutionId: jspb.Message.getFieldWithDefault(msg, 22, ""),
    collectionFinalName: jspb.Message.getFieldWithDefault(msg, 23, ""),
    method: jspb.Message.getFieldWithDefault(msg, 24, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.veidemann.api.log.v1.CrawlLog}
 */
proto.veidemann.api.log.v1.CrawlLog.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.veidemann.api.log.v1.CrawlLog;
  return proto.veidemann.api.log.v1.CrawlLog.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.veidemann.api.log.v1.CrawlLog} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.veidemann.api.log.v1.CrawlLog}
 */
proto.veidemann.api.log.v1.CrawlLog.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setWarcId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimeStamp(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStatusCode(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSize(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestedUri(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setResponseUri(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setDiscoveryPath(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setReferrer(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setContentType(value);
      break;
    case 11:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setFetchTimeStamp(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFetchTimeMs(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setBlockDigest(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setPayloadDigest(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setStorageRef(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setRecordType(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setWarcRefersTo(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setIpAddress(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setExecutionId(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRetries(value);
      break;
    case 21:
      var value = new commons_v1_resources_pb.Error;
      reader.readMessage(value,commons_v1_resources_pb.Error.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    case 22:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobExecutionId(value);
      break;
    case 23:
      var value = /** @type {string} */ (reader.readString());
      msg.setCollectionFinalName(value);
      break;
    case 24:
      var value = /** @type {string} */ (reader.readString());
      msg.setMethod(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.veidemann.api.log.v1.CrawlLog.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.veidemann.api.log.v1.CrawlLog} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.log.v1.CrawlLog.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWarcId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTimeStamp();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getStatusCode();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getSize();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getRequestedUri();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getResponseUri();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getDiscoveryPath();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getReferrer();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getContentType();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getFetchTimeStamp();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getFetchTimeMs();
  if (f !== 0) {
    writer.writeInt64(
      12,
      f
    );
  }
  f = message.getBlockDigest();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getPayloadDigest();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getStorageRef();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getRecordType();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getWarcRefersTo();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getIpAddress();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getExecutionId();
  if (f.length > 0) {
    writer.writeString(
      19,
      f
    );
  }
  f = message.getRetries();
  if (f !== 0) {
    writer.writeInt32(
      20,
      f
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      commons_v1_resources_pb.Error.serializeBinaryToWriter
    );
  }
  f = message.getJobExecutionId();
  if (f.length > 0) {
    writer.writeString(
      22,
      f
    );
  }
  f = message.getCollectionFinalName();
  if (f.length > 0) {
    writer.writeString(
      23,
      f
    );
  }
  f = message.getMethod();
  if (f.length > 0) {
    writer.writeString(
      24,
      f
    );
  }
};


/**
 * optional string warc_id = 1;
 * @return {string}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getWarcId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setWarcId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp time_stamp = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getTimeStamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
*/
proto.veidemann.api.log.v1.CrawlLog.prototype.setTimeStamp = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.clearTimeStamp = function() {
  return this.setTimeStamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.hasTimeStamp = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 status_code = 4;
 * @return {number}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getStatusCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setStatusCode = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 size = 5;
 * @return {number}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setSize = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string requested_uri = 6;
 * @return {string}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getRequestedUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setRequestedUri = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string response_uri = 7;
 * @return {string}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getResponseUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setResponseUri = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string discovery_path = 8;
 * @return {string}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getDiscoveryPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setDiscoveryPath = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string referrer = 9;
 * @return {string}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getReferrer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setReferrer = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string content_type = 10;
 * @return {string}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getContentType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setContentType = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional google.protobuf.Timestamp fetch_time_stamp = 11;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getFetchTimeStamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 11));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
*/
proto.veidemann.api.log.v1.CrawlLog.prototype.setFetchTimeStamp = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.clearFetchTimeStamp = function() {
  return this.setFetchTimeStamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.hasFetchTimeStamp = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional int64 fetch_time_ms = 12;
 * @return {number}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getFetchTimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setFetchTimeMs = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional string block_digest = 13;
 * @return {string}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getBlockDigest = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setBlockDigest = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string payload_digest = 14;
 * @return {string}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getPayloadDigest = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setPayloadDigest = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional string storage_ref = 15;
 * @return {string}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getStorageRef = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setStorageRef = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional string record_type = 16;
 * @return {string}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getRecordType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setRecordType = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional string warc_refers_to = 17;
 * @return {string}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getWarcRefersTo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setWarcRefersTo = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional string ip_address = 18;
 * @return {string}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getIpAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setIpAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 18, value);
};


/**
 * optional string execution_id = 19;
 * @return {string}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getExecutionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setExecutionId = function(value) {
  return jspb.Message.setProto3StringField(this, 19, value);
};


/**
 * optional int32 retries = 20;
 * @return {number}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getRetries = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setRetries = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};


/**
 * optional veidemann.api.commons.v1.Error error = 21;
 * @return {?proto.veidemann.api.commons.v1.Error}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getError = function() {
  return /** @type{?proto.veidemann.api.commons.v1.Error} */ (
    jspb.Message.getWrapperField(this, commons_v1_resources_pb.Error, 21));
};


/**
 * @param {?proto.veidemann.api.commons.v1.Error|undefined} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
*/
proto.veidemann.api.log.v1.CrawlLog.prototype.setError = function(value) {
  return jspb.Message.setWrapperField(this, 21, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.hasError = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional string job_execution_id = 22;
 * @return {string}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getJobExecutionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 22, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setJobExecutionId = function(value) {
  return jspb.Message.setProto3StringField(this, 22, value);
};


/**
 * optional string collection_final_name = 23;
 * @return {string}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getCollectionFinalName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 23, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setCollectionFinalName = function(value) {
  return jspb.Message.setProto3StringField(this, 23, value);
};


/**
 * optional string method = 24;
 * @return {string}
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.getMethod = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 24, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.CrawlLog} returns this
 */
proto.veidemann.api.log.v1.CrawlLog.prototype.setMethod = function(value) {
  return jspb.Message.setProto3StringField(this, 24, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.veidemann.api.log.v1.PageLog.repeatedFields_ = [10,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.veidemann.api.log.v1.PageLog.prototype.toObject = function(opt_includeInstance) {
  return proto.veidemann.api.log.v1.PageLog.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.veidemann.api.log.v1.PageLog} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.log.v1.PageLog.toObject = function(includeInstance, msg) {
  var f, obj = {
    warcId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    uri: jspb.Message.getFieldWithDefault(msg, 2, ""),
    executionId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    referrer: jspb.Message.getFieldWithDefault(msg, 4, ""),
    jobExecutionId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    collectionFinalName: jspb.Message.getFieldWithDefault(msg, 6, ""),
    method: jspb.Message.getFieldWithDefault(msg, 7, ""),
    resourceList: jspb.Message.toObjectList(msg.getResourceList(),
    proto.veidemann.api.log.v1.PageLog.Resource.toObject, includeInstance),
    outlinkList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.veidemann.api.log.v1.PageLog}
 */
proto.veidemann.api.log.v1.PageLog.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.veidemann.api.log.v1.PageLog;
  return proto.veidemann.api.log.v1.PageLog.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.veidemann.api.log.v1.PageLog} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.veidemann.api.log.v1.PageLog}
 */
proto.veidemann.api.log.v1.PageLog.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setWarcId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUri(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setExecutionId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setReferrer(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobExecutionId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCollectionFinalName(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setMethod(value);
      break;
    case 10:
      var value = new proto.veidemann.api.log.v1.PageLog.Resource;
      reader.readMessage(value,proto.veidemann.api.log.v1.PageLog.Resource.deserializeBinaryFromReader);
      msg.addResource(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addOutlink(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.veidemann.api.log.v1.PageLog.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.veidemann.api.log.v1.PageLog.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.veidemann.api.log.v1.PageLog} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.log.v1.PageLog.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWarcId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUri();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getExecutionId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getReferrer();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getJobExecutionId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCollectionFinalName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getMethod();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getResourceList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      proto.veidemann.api.log.v1.PageLog.Resource.serializeBinaryToWriter
    );
  }
  f = message.getOutlinkList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.toObject = function(opt_includeInstance) {
  return proto.veidemann.api.log.v1.PageLog.Resource.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.veidemann.api.log.v1.PageLog.Resource} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.log.v1.PageLog.Resource.toObject = function(includeInstance, msg) {
  var f, obj = {
    uri: jspb.Message.getFieldWithDefault(msg, 1, ""),
    fromCache: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    renderable: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    resourceType: jspb.Message.getFieldWithDefault(msg, 4, ""),
    contentType: jspb.Message.getFieldWithDefault(msg, 5, ""),
    statusCode: jspb.Message.getFieldWithDefault(msg, 6, 0),
    discoveryPath: jspb.Message.getFieldWithDefault(msg, 7, ""),
    warcId: jspb.Message.getFieldWithDefault(msg, 8, ""),
    referrer: jspb.Message.getFieldWithDefault(msg, 9, ""),
    error: (f = msg.getError()) && commons_v1_resources_pb.Error.toObject(includeInstance, f),
    method: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.veidemann.api.log.v1.PageLog.Resource}
 */
proto.veidemann.api.log.v1.PageLog.Resource.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.veidemann.api.log.v1.PageLog.Resource;
  return proto.veidemann.api.log.v1.PageLog.Resource.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.veidemann.api.log.v1.PageLog.Resource} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.veidemann.api.log.v1.PageLog.Resource}
 */
proto.veidemann.api.log.v1.PageLog.Resource.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUri(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFromCache(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRenderable(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setResourceType(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setContentType(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStatusCode(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setDiscoveryPath(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setWarcId(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setReferrer(value);
      break;
    case 10:
      var value = new commons_v1_resources_pb.Error;
      reader.readMessage(value,commons_v1_resources_pb.Error.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setMethod(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.veidemann.api.log.v1.PageLog.Resource.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.veidemann.api.log.v1.PageLog.Resource} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.log.v1.PageLog.Resource.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUri();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFromCache();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getRenderable();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getResourceType();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getContentType();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getStatusCode();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getDiscoveryPath();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getWarcId();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getReferrer();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      commons_v1_resources_pb.Error.serializeBinaryToWriter
    );
  }
  f = message.getMethod();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional string uri = 1;
 * @return {string}
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.getUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.PageLog.Resource} returns this
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.setUri = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool from_cache = 2;
 * @return {boolean}
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.getFromCache = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.veidemann.api.log.v1.PageLog.Resource} returns this
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.setFromCache = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool renderable = 3;
 * @return {boolean}
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.getRenderable = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.veidemann.api.log.v1.PageLog.Resource} returns this
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.setRenderable = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional string resource_type = 4;
 * @return {string}
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.getResourceType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.PageLog.Resource} returns this
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.setResourceType = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string content_type = 5;
 * @return {string}
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.getContentType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.PageLog.Resource} returns this
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.setContentType = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int32 status_code = 6;
 * @return {number}
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.getStatusCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.veidemann.api.log.v1.PageLog.Resource} returns this
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.setStatusCode = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string discovery_path = 7;
 * @return {string}
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.getDiscoveryPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.PageLog.Resource} returns this
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.setDiscoveryPath = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string warc_id = 8;
 * @return {string}
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.getWarcId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.PageLog.Resource} returns this
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.setWarcId = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string referrer = 9;
 * @return {string}
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.getReferrer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.PageLog.Resource} returns this
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.setReferrer = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional veidemann.api.commons.v1.Error error = 10;
 * @return {?proto.veidemann.api.commons.v1.Error}
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.getError = function() {
  return /** @type{?proto.veidemann.api.commons.v1.Error} */ (
    jspb.Message.getWrapperField(this, commons_v1_resources_pb.Error, 10));
};


/**
 * @param {?proto.veidemann.api.commons.v1.Error|undefined} value
 * @return {!proto.veidemann.api.log.v1.PageLog.Resource} returns this
*/
proto.veidemann.api.log.v1.PageLog.Resource.prototype.setError = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.veidemann.api.log.v1.PageLog.Resource} returns this
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.hasError = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional string method = 11;
 * @return {string}
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.getMethod = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.PageLog.Resource} returns this
 */
proto.veidemann.api.log.v1.PageLog.Resource.prototype.setMethod = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string warc_id = 1;
 * @return {string}
 */
proto.veidemann.api.log.v1.PageLog.prototype.getWarcId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.PageLog} returns this
 */
proto.veidemann.api.log.v1.PageLog.prototype.setWarcId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string uri = 2;
 * @return {string}
 */
proto.veidemann.api.log.v1.PageLog.prototype.getUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.PageLog} returns this
 */
proto.veidemann.api.log.v1.PageLog.prototype.setUri = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string execution_id = 3;
 * @return {string}
 */
proto.veidemann.api.log.v1.PageLog.prototype.getExecutionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.PageLog} returns this
 */
proto.veidemann.api.log.v1.PageLog.prototype.setExecutionId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string referrer = 4;
 * @return {string}
 */
proto.veidemann.api.log.v1.PageLog.prototype.getReferrer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.PageLog} returns this
 */
proto.veidemann.api.log.v1.PageLog.prototype.setReferrer = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string job_execution_id = 5;
 * @return {string}
 */
proto.veidemann.api.log.v1.PageLog.prototype.getJobExecutionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.PageLog} returns this
 */
proto.veidemann.api.log.v1.PageLog.prototype.setJobExecutionId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string collection_final_name = 6;
 * @return {string}
 */
proto.veidemann.api.log.v1.PageLog.prototype.getCollectionFinalName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.PageLog} returns this
 */
proto.veidemann.api.log.v1.PageLog.prototype.setCollectionFinalName = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string method = 7;
 * @return {string}
 */
proto.veidemann.api.log.v1.PageLog.prototype.getMethod = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.log.v1.PageLog} returns this
 */
proto.veidemann.api.log.v1.PageLog.prototype.setMethod = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * repeated Resource resource = 10;
 * @return {!Array<!proto.veidemann.api.log.v1.PageLog.Resource>}
 */
proto.veidemann.api.log.v1.PageLog.prototype.getResourceList = function() {
  return /** @type{!Array<!proto.veidemann.api.log.v1.PageLog.Resource>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.veidemann.api.log.v1.PageLog.Resource, 10));
};


/**
 * @param {!Array<!proto.veidemann.api.log.v1.PageLog.Resource>} value
 * @return {!proto.veidemann.api.log.v1.PageLog} returns this
*/
proto.veidemann.api.log.v1.PageLog.prototype.setResourceList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.veidemann.api.log.v1.PageLog.Resource=} opt_value
 * @param {number=} opt_index
 * @return {!proto.veidemann.api.log.v1.PageLog.Resource}
 */
proto.veidemann.api.log.v1.PageLog.prototype.addResource = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.veidemann.api.log.v1.PageLog.Resource, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.veidemann.api.log.v1.PageLog} returns this
 */
proto.veidemann.api.log.v1.PageLog.prototype.clearResourceList = function() {
  return this.setResourceList([]);
};


/**
 * repeated string outlink = 11;
 * @return {!Array<string>}
 */
proto.veidemann.api.log.v1.PageLog.prototype.getOutlinkList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.veidemann.api.log.v1.PageLog} returns this
 */
proto.veidemann.api.log.v1.PageLog.prototype.setOutlinkList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.veidemann.api.log.v1.PageLog} returns this
 */
proto.veidemann.api.log.v1.PageLog.prototype.addOutlink = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.veidemann.api.log.v1.PageLog} returns this
 */
proto.veidemann.api.log.v1.PageLog.prototype.clearOutlinkList = function() {
  return this.setOutlinkList([]);
};


goog.object.extend(exports, proto.veidemann.api.log.v1);
