export enum Kind {
  UNDEFINED = 0,
  CRAWLENTITY = 5,
  SEED = 6,
  CRAWLJOB = 7,
  CRAWLCONFIG = 8,
  CRAWLSCHEDULECONFIG = 9,
  BROWSERCONFIG = 10,
  POLITENESSCONFIG = 11,
  BROWSERSCRIPT = 12,
  CRAWLHOSTGROUPCONFIG = 13,
  ROLEMAPPING = 14,
  COLLECTION = 15,
}
